-- BASED ON CHICAGO_TAXI schema in demodb

CREATE OR REPLACE CONNECTION EXASOL_DEMO_DATA
TO '' --Need to fill in where this data resides
USER '' -- hope it's not needed
IDENTIFIED BY '' -- hope it's not needed


CREATE SCHEMA CHICAGO_TAXI;

CREATE TABLE 
    "CENSUS_TRACTS" 
    ( 
        "CENSUS_TRACT_ID" DECIMAL(11,0) NOT NULL, 
        "TRACTCE10"       SMALLINT, 
        "NAME10"          SMALLINT, 
        "NAMELSAD10"      VARCHAR(100), 
        "COMMAREA"        SMALLINT, 
        "NOTES"           VARCHAR(1000) 
    );
    
CREATE TABLE 
    "COMMUNITY_AREAS" 
    ( 
        "COMMUNITY_AREA_ID" SMALLINT NOT NULL, 
        "COMMUNITY_NAME"    VARCHAR(100) 
    );
    
CREATE TABLE 
    "COMPANIES" 
    ( 
        "COMPANY_SID" SMALLINT IDENTITY NOT NULL, 
        "COMPANY"     VARCHAR(100) NOT NULL 
    );
    
CREATE TABLE 
    "PAYMENT_TYPES" 
    ( 
        "PAYMENT_TYPE_SID" SMALLINT IDENTITY NOT NULL, 
        "PAYMENT_TYPE"     VARCHAR(100) 
    );
    
CREATE TABLE 
    "TAXIS" 
    ( 
        "TAXI_SID" SMALLINT IDENTITY NOT NULL, 
        "TAXI_ID"  VARCHAR(128) NOT NULL 
    );
    
CREATE TABLE 
    "TAXI_TRIPS" 
    ( 
        "TRIP_ID"                    CHAR(40) ASCII NOT NULL, 
        "TAXI_SID"                   SMALLINT, 
        "TRIP_START_TIMESTAMP"       TIMESTAMP, 
        "TRIP_END_TIMESTAMP"         TIMESTAMP, 
        "TRIP_SECONDS"               SMALLINT, 
        "TRIP_MILES"                 DECIMAL(9,2), 
        "PICKUP_CENSUS_TRACT"        DECIMAL(11,0), 
        "DROPOFF_CENSUS_TRACT"       DECIMAL(11,0), 
        "PICKUP_COMMUNITY_AREA"      SMALLINT, 
        "DROPOFF_COMMUNITY_AREA"     SMALLINT, 
        "FARE"                       DECIMAL(9,2), 
        "TIPS"                       DECIMAL(9,2), 
        "TOLLS"                      DECIMAL(9,2), 
        "EXTRAS"                     DECIMAL(9,2), 
        "TRIP_TOTAL"                 DECIMAL(9,2), 
        "PAYMENT_TYPE_SID"           SMALLINT, 
        "COMPANY_SID"                SMALLINT, 
        "PICKUP_CENTROID_LATITUDE"   DECIMAL(18,9), 
        "PICKUP_CENTROID_LONGITUDE"  DECIMAL(18,9), 
        "DROPOFF_CENTROID_LATITUDE"  DECIMAL(18,9), 
        "DROPOFF_CENTROID_LONGITUDE" DECIMAL(18,9) 
    );
    
ALTER TABLE "CENSUS_TRACTS" ADD PRIMARY KEY ("CENSUS_TRACT_ID");
ALTER TABLE "COMMUNITY_AREAS" ADD PRIMARY KEY ("COMMUNITY_AREA_ID");
ALTER TABLE "COMPANIES" ADD PRIMARY KEY ("COMPANY_SID");
ALTER TABLE "PAYMENT_TYPES" ADD PRIMARY KEY ("PAYMENT_TYPE_SID");
ALTER TABLE "TAXIS" ADD PRIMARY KEY ("TAXI_SID");
ALTER TABLE "TAXI_TRIPS" ADD PRIMARY KEY ("TRIP_ID");
ALTER TABLE "TAXI_TRIPS" ADD FOREIGN KEY ("TAXI_SID") REFERENCES "TAXIS" ("TAXI_SID");
ALTER TABLE "TAXI_TRIPS" ADD FOREIGN KEY ("PICKUP_CENSUS_TRACT") REFERENCES "CENSUS_TRACTS"("CENSUS_TRACT_ID");
ALTER TABLE "TAXI_TRIPS" ADD FOREIGN KEY ("DROPOFF_CENSUS_TRACT") REFERENCES "CENSUS_TRACTS"("CENSUS_TRACT_ID");
ALTER TABLE "TAXI_TRIPS" ADD FOREIGN KEY ("DROPOFF_COMMUNITY_AREA") REFERENCES "COMMUNITY_AREAS"("COMMUNITY_AREA_ID");
ALTER TABLE "TAXI_TRIPS" ADD FOREIGN KEY ("PICKUP_COMMUNITY_AREA") REFERENCES "COMMUNITY_AREAS"("COMMUNITY_AREA_ID");
ALTER TABLE "TAXI_TRIPS" ADD FOREIGN KEY ("PAYMENT_TYPE_SID") REFERENCES "PAYMENT_TYPES"("PAYMENT_TYPE_SID");
ALTER TABLE "TAXI_TRIPS" ADD FOREIGN KEY ("COMPANY_SID") REFERENCES "COMPANIES" ("COMPANY_SID");

IMPORT INTO CHICAGO_TAXI.CENSUS_TRACTS FROM CSV AT EXASOL_DEMO_DATA FILE 'chicago_taxi/census_tracts.csv';
IMPORT INTO CHICAGO_TAXI.COMMUNITY_AREAS FROM CSV AT EXASOL_DEMO_DATA FILE 'chicago_taxi/community_areas.csv';
IMPORT INTO CHICAGO_TAXI.COMPANIES FROM CSV AT EXASOL_DEMO_DATA FILE 'chicago_taxi/companies.csv';
IMPORT INTO CHICAGO_TAXI.PAYMENT_TYPES FROM CSV AT EXASOL_DEMO_DATA FILE 'chicago_taxi/payment_types.csv';
IMPORT INTO CHICAGO_TAXI.TAXIS FROM CSV AT EXASOL_DEMO_DATA FILE 'chicago_taxi/taxis.csv';

-- Use multiple files to improve performance and have all nodes import in parallel
IMPORT INTO CHICAGO_TAXI.TAXI_TRIPS FROM CSV AT EXASOL_DEMO_DATA FILE 'chicago_taxi/taxi_trips_pt1.csv' FILE 'chicago_taxi/taxi_trips_pt2.csv' FILE 'chicago_taxi/taxi_trips_pt3.csv' FILE 'chicago_taxi/taxi_trips_pt4.csv';

SELECT 'All data imported! Enjoy exploring the Chicago Taxi dataset!';

